[build]
  publish = "frontend"

[[redirects]]
  from = "/api/summarize"
  to = "https://text-summarizer-api-gq03.onrender.com/summarize/"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "https://text-summarizer-api-gq03.onrender.com/health"
  status = 200
  force = true
